/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppVendorsIndexRouteImport } from './routes/app.vendors.index'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppRfqsIndexRouteImport } from './routes/app.rfqs.index'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppQuotationsIndexRouteImport } from './routes/app.quotations.index'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/app.purchase-orders.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app.notifications.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app.invoices.index'
import { Route as AppComparisonIndexRouteImport } from './routes/app.comparison.index'
import { Route as AppApprovalsIndexRouteImport } from './routes/app.approvals.index'
import { Route as AppActivityIndexRouteImport } from './routes/app.activity.index'
import { Route as AppVendorsPerformanceRouteImport } from './routes/app.vendors.performance'
import { Route as AppVendorsNewRouteImport } from './routes/app.vendors.new'
import { Route as AppVendorsMapRouteImport } from './routes/app.vendors.map'
import { Route as AppVendorsDocumentsRouteImport } from './routes/app.vendors.documents'
import { Route as AppVendorsCategoriesRouteImport } from './routes/app.vendors.categories'
import { Route as AppVendorsIdRouteImport } from './routes/app.vendors.$id'
import { Route as AppSettingsUsersRouteImport } from './routes/app.settings.users'
import { Route as AppSettingsTaxRouteImport } from './routes/app.settings.tax'
import { Route as AppSettingsRolesRouteImport } from './routes/app.settings.roles'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsApprovalRulesRouteImport } from './routes/app.settings.approval-rules'
import { Route as AppRfqsNewRouteImport } from './routes/app.rfqs.new'
import { Route as AppRfqsIdRouteImport } from './routes/app.rfqs.$id'
import { Route as AppReportsVendorsRouteImport } from './routes/app.reports.vendors'
import { Route as AppReportsTrendsRouteImport } from './routes/app.reports.trends'
import { Route as AppReportsSpendRouteImport } from './routes/app.reports.spend'
import { Route as AppReportsExportRouteImport } from './routes/app.reports.export'
import { Route as AppQuotationsSubmitRouteImport } from './routes/app.quotations.submit'
import { Route as AppQuotationsHistoryRouteImport } from './routes/app.quotations.history'
import { Route as AppQuotationsIdRouteImport } from './routes/app.quotations.$id'
import { Route as AppPurchaseOrdersNewRouteImport } from './routes/app.purchase-orders.new'
import { Route as AppPurchaseOrdersIdRouteImport } from './routes/app.purchase-orders.$id'
import { Route as AppNotificationsHistoryRouteImport } from './routes/app.notifications.history'
import { Route as AppInvoicesNewRouteImport } from './routes/app.invoices.new'
import { Route as AppInvoicesIdRouteImport } from './routes/app.invoices.$id'
import { Route as AppComparisonRankingRouteImport } from './routes/app.comparison.ranking'
import { Route as AppComparisonEvaluationRouteImport } from './routes/app.comparison.evaluation'
import { Route as AppApprovalsTimelineRouteImport } from './routes/app.approvals.timeline'
import { Route as AppApprovalsHistoryRouteImport } from './routes/app.approvals.history'
import { Route as AppApprovalsIdRouteImport } from './routes/app.approvals.$id'
import { Route as AppActivityAuditRouteImport } from './routes/app.activity.audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqsIndexRoute = AppRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppComparisonIndexRoute = AppComparisonIndexRouteImport.update({
  id: '/comparison/',
  path: '/comparison/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsIndexRoute = AppApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsPerformanceRoute = AppVendorsPerformanceRouteImport.update({
  id: '/vendors/performance',
  path: '/vendors/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsNewRoute = AppVendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsMapRoute = AppVendorsMapRouteImport.update({
  id: '/vendors/map',
  path: '/vendors/map',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsDocumentsRoute = AppVendorsDocumentsRouteImport.update({
  id: '/vendors/documents',
  path: '/vendors/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsCategoriesRoute = AppVendorsCategoriesRouteImport.update({
  id: '/vendors/categories',
  path: '/vendors/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTaxRoute = AppSettingsTaxRouteImport.update({
  id: '/settings/tax',
  path: '/settings/tax',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsApprovalRulesRoute =
  AppSettingsApprovalRulesRouteImport.update({
    id: '/settings/approval-rules',
    path: '/settings/approval-rules',
    getParentRoute: () => AppRoute,
  } as any)
const AppRfqsNewRoute = AppRfqsNewRouteImport.update({
  id: '/rfqs/new',
  path: '/rfqs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqsIdRoute = AppRfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsVendorsRoute = AppReportsVendorsRouteImport.update({
  id: '/reports/vendors',
  path: '/reports/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTrendsRoute = AppReportsTrendsRouteImport.update({
  id: '/reports/trends',
  path: '/reports/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSpendRoute = AppReportsSpendRouteImport.update({
  id: '/reports/spend',
  path: '/reports/spend',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsExportRoute = AppReportsExportRouteImport.update({
  id: '/reports/export',
  path: '/reports/export',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsSubmitRoute = AppQuotationsSubmitRouteImport.update({
  id: '/quotations/submit',
  path: '/quotations/submit',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsHistoryRoute = AppQuotationsHistoryRouteImport.update({
  id: '/quotations/history',
  path: '/quotations/history',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIdRoute = AppQuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersNewRoute = AppPurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIdRoute = AppPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsHistoryRoute = AppNotificationsHistoryRouteImport.update({
  id: '/notifications/history',
  path: '/notifications/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppComparisonRankingRoute = AppComparisonRankingRouteImport.update({
  id: '/comparison/ranking',
  path: '/comparison/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppComparisonEvaluationRoute = AppComparisonEvaluationRouteImport.update({
  id: '/comparison/evaluation',
  path: '/comparison/evaluation',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsTimelineRoute = AppApprovalsTimelineRouteImport.update({
  id: '/approvals/timeline',
  path: '/approvals/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsHistoryRoute = AppApprovalsHistoryRouteImport.update({
  id: '/approvals/history',
  path: '/approvals/history',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsIdRoute = AppApprovalsIdRouteImport.update({
  id: '/approvals/$id',
  path: '/approvals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityAuditRoute = AppActivityAuditRouteImport.update({
  id: '/activity/audit',
  path: '/activity/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/risk': typeof AppRiskRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/activity/audit': typeof AppActivityAuditRoute
  '/app/approvals/$id': typeof AppApprovalsIdRoute
  '/app/approvals/history': typeof AppApprovalsHistoryRoute
  '/app/approvals/timeline': typeof AppApprovalsTimelineRoute
  '/app/comparison/evaluation': typeof AppComparisonEvaluationRoute
  '/app/comparison/ranking': typeof AppComparisonRankingRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/notifications/history': typeof AppNotificationsHistoryRoute
  '/app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/app/quotations/$id': typeof AppQuotationsIdRoute
  '/app/quotations/history': typeof AppQuotationsHistoryRoute
  '/app/quotations/submit': typeof AppQuotationsSubmitRoute
  '/app/reports/export': typeof AppReportsExportRoute
  '/app/reports/spend': typeof AppReportsSpendRoute
  '/app/reports/trends': typeof AppReportsTrendsRoute
  '/app/reports/vendors': typeof AppReportsVendorsRoute
  '/app/rfqs/$id': typeof AppRfqsIdRoute
  '/app/rfqs/new': typeof AppRfqsNewRoute
  '/app/settings/approval-rules': typeof AppSettingsApprovalRulesRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/roles': typeof AppSettingsRolesRoute
  '/app/settings/tax': typeof AppSettingsTaxRoute
  '/app/settings/users': typeof AppSettingsUsersRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/app/vendors/categories': typeof AppVendorsCategoriesRoute
  '/app/vendors/documents': typeof AppVendorsDocumentsRoute
  '/app/vendors/map': typeof AppVendorsMapRoute
  '/app/vendors/new': typeof AppVendorsNewRoute
  '/app/vendors/performance': typeof AppVendorsPerformanceRoute
  '/app/activity/': typeof AppActivityIndexRoute
  '/app/approvals/': typeof AppApprovalsIndexRoute
  '/app/comparison/': typeof AppComparisonIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/app/quotations/': typeof AppQuotationsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/rfqs/': typeof AppRfqsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/vendors/': typeof AppVendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/risk': typeof AppRiskRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/app/activity/audit': typeof AppActivityAuditRoute
  '/app/approvals/$id': typeof AppApprovalsIdRoute
  '/app/approvals/history': typeof AppApprovalsHistoryRoute
  '/app/approvals/timeline': typeof AppApprovalsTimelineRoute
  '/app/comparison/evaluation': typeof AppComparisonEvaluationRoute
  '/app/comparison/ranking': typeof AppComparisonRankingRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/notifications/history': typeof AppNotificationsHistoryRoute
  '/app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/app/quotations/$id': typeof AppQuotationsIdRoute
  '/app/quotations/history': typeof AppQuotationsHistoryRoute
  '/app/quotations/submit': typeof AppQuotationsSubmitRoute
  '/app/reports/export': typeof AppReportsExportRoute
  '/app/reports/spend': typeof AppReportsSpendRoute
  '/app/reports/trends': typeof AppReportsTrendsRoute
  '/app/reports/vendors': typeof AppReportsVendorsRoute
  '/app/rfqs/$id': typeof AppRfqsIdRoute
  '/app/rfqs/new': typeof AppRfqsNewRoute
  '/app/settings/approval-rules': typeof AppSettingsApprovalRulesRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/roles': typeof AppSettingsRolesRoute
  '/app/settings/tax': typeof AppSettingsTaxRoute
  '/app/settings/users': typeof AppSettingsUsersRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/app/vendors/categories': typeof AppVendorsCategoriesRoute
  '/app/vendors/documents': typeof AppVendorsDocumentsRoute
  '/app/vendors/map': typeof AppVendorsMapRoute
  '/app/vendors/new': typeof AppVendorsNewRoute
  '/app/vendors/performance': typeof AppVendorsPerformanceRoute
  '/app/activity': typeof AppActivityIndexRoute
  '/app/approvals': typeof AppApprovalsIndexRoute
  '/app/comparison': typeof AppComparisonIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/app/quotations': typeof AppQuotationsIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/rfqs': typeof AppRfqsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/vendors': typeof AppVendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/risk': typeof AppRiskRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/activity/audit': typeof AppActivityAuditRoute
  '/app/approvals/$id': typeof AppApprovalsIdRoute
  '/app/approvals/history': typeof AppApprovalsHistoryRoute
  '/app/approvals/timeline': typeof AppApprovalsTimelineRoute
  '/app/comparison/evaluation': typeof AppComparisonEvaluationRoute
  '/app/comparison/ranking': typeof AppComparisonRankingRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/notifications/history': typeof AppNotificationsHistoryRoute
  '/app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/app/quotations/$id': typeof AppQuotationsIdRoute
  '/app/quotations/history': typeof AppQuotationsHistoryRoute
  '/app/quotations/submit': typeof AppQuotationsSubmitRoute
  '/app/reports/export': typeof AppReportsExportRoute
  '/app/reports/spend': typeof AppReportsSpendRoute
  '/app/reports/trends': typeof AppReportsTrendsRoute
  '/app/reports/vendors': typeof AppReportsVendorsRoute
  '/app/rfqs/$id': typeof AppRfqsIdRoute
  '/app/rfqs/new': typeof AppRfqsNewRoute
  '/app/settings/approval-rules': typeof AppSettingsApprovalRulesRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/roles': typeof AppSettingsRolesRoute
  '/app/settings/tax': typeof AppSettingsTaxRoute
  '/app/settings/users': typeof AppSettingsUsersRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/app/vendors/categories': typeof AppVendorsCategoriesRoute
  '/app/vendors/documents': typeof AppVendorsDocumentsRoute
  '/app/vendors/map': typeof AppVendorsMapRoute
  '/app/vendors/new': typeof AppVendorsNewRoute
  '/app/vendors/performance': typeof AppVendorsPerformanceRoute
  '/app/activity/': typeof AppActivityIndexRoute
  '/app/approvals/': typeof AppApprovalsIndexRoute
  '/app/comparison/': typeof AppComparisonIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/app/quotations/': typeof AppQuotationsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/rfqs/': typeof AppRfqsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/vendors/': typeof AppVendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/risk'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/app/'
    | '/app/activity/audit'
    | '/app/approvals/$id'
    | '/app/approvals/history'
    | '/app/approvals/timeline'
    | '/app/comparison/evaluation'
    | '/app/comparison/ranking'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/notifications/history'
    | '/app/purchase-orders/$id'
    | '/app/purchase-orders/new'
    | '/app/quotations/$id'
    | '/app/quotations/history'
    | '/app/quotations/submit'
    | '/app/reports/export'
    | '/app/reports/spend'
    | '/app/reports/trends'
    | '/app/reports/vendors'
    | '/app/rfqs/$id'
    | '/app/rfqs/new'
    | '/app/settings/approval-rules'
    | '/app/settings/notifications'
    | '/app/settings/roles'
    | '/app/settings/tax'
    | '/app/settings/users'
    | '/app/vendors/$id'
    | '/app/vendors/categories'
    | '/app/vendors/documents'
    | '/app/vendors/map'
    | '/app/vendors/new'
    | '/app/vendors/performance'
    | '/app/activity/'
    | '/app/approvals/'
    | '/app/comparison/'
    | '/app/invoices/'
    | '/app/notifications/'
    | '/app/purchase-orders/'
    | '/app/quotations/'
    | '/app/reports/'
    | '/app/rfqs/'
    | '/app/settings/'
    | '/app/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/dashboard'
    | '/app/risk'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/app'
    | '/app/activity/audit'
    | '/app/approvals/$id'
    | '/app/approvals/history'
    | '/app/approvals/timeline'
    | '/app/comparison/evaluation'
    | '/app/comparison/ranking'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/notifications/history'
    | '/app/purchase-orders/$id'
    | '/app/purchase-orders/new'
    | '/app/quotations/$id'
    | '/app/quotations/history'
    | '/app/quotations/submit'
    | '/app/reports/export'
    | '/app/reports/spend'
    | '/app/reports/trends'
    | '/app/reports/vendors'
    | '/app/rfqs/$id'
    | '/app/rfqs/new'
    | '/app/settings/approval-rules'
    | '/app/settings/notifications'
    | '/app/settings/roles'
    | '/app/settings/tax'
    | '/app/settings/users'
    | '/app/vendors/$id'
    | '/app/vendors/categories'
    | '/app/vendors/documents'
    | '/app/vendors/map'
    | '/app/vendors/new'
    | '/app/vendors/performance'
    | '/app/activity'
    | '/app/approvals'
    | '/app/comparison'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/reports'
    | '/app/rfqs'
    | '/app/settings'
    | '/app/vendors'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/risk'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/app/'
    | '/app/activity/audit'
    | '/app/approvals/$id'
    | '/app/approvals/history'
    | '/app/approvals/timeline'
    | '/app/comparison/evaluation'
    | '/app/comparison/ranking'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/notifications/history'
    | '/app/purchase-orders/$id'
    | '/app/purchase-orders/new'
    | '/app/quotations/$id'
    | '/app/quotations/history'
    | '/app/quotations/submit'
    | '/app/reports/export'
    | '/app/reports/spend'
    | '/app/reports/trends'
    | '/app/reports/vendors'
    | '/app/rfqs/$id'
    | '/app/rfqs/new'
    | '/app/settings/approval-rules'
    | '/app/settings/notifications'
    | '/app/settings/roles'
    | '/app/settings/tax'
    | '/app/settings/users'
    | '/app/vendors/$id'
    | '/app/vendors/categories'
    | '/app/vendors/documents'
    | '/app/vendors/map'
    | '/app/vendors/new'
    | '/app/vendors/performance'
    | '/app/activity/'
    | '/app/approvals/'
    | '/app/comparison/'
    | '/app/invoices/'
    | '/app/notifications/'
    | '/app/purchase-orders/'
    | '/app/quotations/'
    | '/app/reports/'
    | '/app/rfqs/'
    | '/app/settings/'
    | '/app/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/': {
      id: '/app/vendors/'
      path: '/vendors'
      fullPath: '/app/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rfqs/': {
      id: '/app/rfqs/'
      path: '/rfqs'
      fullPath: '/app/rfqs/'
      preLoaderRoute: typeof AppRfqsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations/': {
      id: '/app/quotations/'
      path: '/quotations'
      fullPath: '/app/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders/': {
      id: '/app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparison/': {
      id: '/app/comparison/'
      path: '/comparison'
      fullPath: '/app/comparison/'
      preLoaderRoute: typeof AppComparisonIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals/': {
      id: '/app/approvals/'
      path: '/approvals'
      fullPath: '/app/approvals/'
      preLoaderRoute: typeof AppApprovalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity/': {
      id: '/app/activity/'
      path: '/activity'
      fullPath: '/app/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/performance': {
      id: '/app/vendors/performance'
      path: '/vendors/performance'
      fullPath: '/app/vendors/performance'
      preLoaderRoute: typeof AppVendorsPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/new': {
      id: '/app/vendors/new'
      path: '/vendors/new'
      fullPath: '/app/vendors/new'
      preLoaderRoute: typeof AppVendorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/map': {
      id: '/app/vendors/map'
      path: '/vendors/map'
      fullPath: '/app/vendors/map'
      preLoaderRoute: typeof AppVendorsMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/documents': {
      id: '/app/vendors/documents'
      path: '/vendors/documents'
      fullPath: '/app/vendors/documents'
      preLoaderRoute: typeof AppVendorsDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/categories': {
      id: '/app/vendors/categories'
      path: '/vendors/categories'
      fullPath: '/app/vendors/categories'
      preLoaderRoute: typeof AppVendorsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/$id': {
      id: '/app/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/app/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/users': {
      id: '/app/settings/users'
      path: '/settings/users'
      fullPath: '/app/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/tax': {
      id: '/app/settings/tax'
      path: '/settings/tax'
      fullPath: '/app/settings/tax'
      preLoaderRoute: typeof AppSettingsTaxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/roles': {
      id: '/app/settings/roles'
      path: '/settings/roles'
      fullPath: '/app/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/approval-rules': {
      id: '/app/settings/approval-rules'
      path: '/settings/approval-rules'
      fullPath: '/app/settings/approval-rules'
      preLoaderRoute: typeof AppSettingsApprovalRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rfqs/new': {
      id: '/app/rfqs/new'
      path: '/rfqs/new'
      fullPath: '/app/rfqs/new'
      preLoaderRoute: typeof AppRfqsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rfqs/$id': {
      id: '/app/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/app/rfqs/$id'
      preLoaderRoute: typeof AppRfqsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/vendors': {
      id: '/app/reports/vendors'
      path: '/reports/vendors'
      fullPath: '/app/reports/vendors'
      preLoaderRoute: typeof AppReportsVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/trends': {
      id: '/app/reports/trends'
      path: '/reports/trends'
      fullPath: '/app/reports/trends'
      preLoaderRoute: typeof AppReportsTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/spend': {
      id: '/app/reports/spend'
      path: '/reports/spend'
      fullPath: '/app/reports/spend'
      preLoaderRoute: typeof AppReportsSpendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/export': {
      id: '/app/reports/export'
      path: '/reports/export'
      fullPath: '/app/reports/export'
      preLoaderRoute: typeof AppReportsExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations/submit': {
      id: '/app/quotations/submit'
      path: '/quotations/submit'
      fullPath: '/app/quotations/submit'
      preLoaderRoute: typeof AppQuotationsSubmitRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations/history': {
      id: '/app/quotations/history'
      path: '/quotations/history'
      fullPath: '/app/quotations/history'
      preLoaderRoute: typeof AppQuotationsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations/$id': {
      id: '/app/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/app/quotations/$id'
      preLoaderRoute: typeof AppQuotationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders/new': {
      id: '/app/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/app/purchase-orders/new'
      preLoaderRoute: typeof AppPurchaseOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders/$id': {
      id: '/app/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/app/purchase-orders/$id'
      preLoaderRoute: typeof AppPurchaseOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/history': {
      id: '/app/notifications/history'
      path: '/notifications/history'
      fullPath: '/app/notifications/history'
      preLoaderRoute: typeof AppNotificationsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/new': {
      id: '/app/invoices/new'
      path: '/invoices/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/$id': {
      id: '/app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/app/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparison/ranking': {
      id: '/app/comparison/ranking'
      path: '/comparison/ranking'
      fullPath: '/app/comparison/ranking'
      preLoaderRoute: typeof AppComparisonRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparison/evaluation': {
      id: '/app/comparison/evaluation'
      path: '/comparison/evaluation'
      fullPath: '/app/comparison/evaluation'
      preLoaderRoute: typeof AppComparisonEvaluationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals/timeline': {
      id: '/app/approvals/timeline'
      path: '/approvals/timeline'
      fullPath: '/app/approvals/timeline'
      preLoaderRoute: typeof AppApprovalsTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals/history': {
      id: '/app/approvals/history'
      path: '/approvals/history'
      fullPath: '/app/approvals/history'
      preLoaderRoute: typeof AppApprovalsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals/$id': {
      id: '/app/approvals/$id'
      path: '/approvals/$id'
      fullPath: '/app/approvals/$id'
      preLoaderRoute: typeof AppApprovalsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity/audit': {
      id: '/app/activity/audit'
      path: '/activity/audit'
      fullPath: '/app/activity/audit'
      preLoaderRoute: typeof AppActivityAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppRiskRoute: typeof AppRiskRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActivityAuditRoute: typeof AppActivityAuditRoute
  AppApprovalsIdRoute: typeof AppApprovalsIdRoute
  AppApprovalsHistoryRoute: typeof AppApprovalsHistoryRoute
  AppApprovalsTimelineRoute: typeof AppApprovalsTimelineRoute
  AppComparisonEvaluationRoute: typeof AppComparisonEvaluationRoute
  AppComparisonRankingRoute: typeof AppComparisonRankingRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppNotificationsHistoryRoute: typeof AppNotificationsHistoryRoute
  AppPurchaseOrdersIdRoute: typeof AppPurchaseOrdersIdRoute
  AppPurchaseOrdersNewRoute: typeof AppPurchaseOrdersNewRoute
  AppQuotationsIdRoute: typeof AppQuotationsIdRoute
  AppQuotationsHistoryRoute: typeof AppQuotationsHistoryRoute
  AppQuotationsSubmitRoute: typeof AppQuotationsSubmitRoute
  AppReportsExportRoute: typeof AppReportsExportRoute
  AppReportsSpendRoute: typeof AppReportsSpendRoute
  AppReportsTrendsRoute: typeof AppReportsTrendsRoute
  AppReportsVendorsRoute: typeof AppReportsVendorsRoute
  AppRfqsIdRoute: typeof AppRfqsIdRoute
  AppRfqsNewRoute: typeof AppRfqsNewRoute
  AppSettingsApprovalRulesRoute: typeof AppSettingsApprovalRulesRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsTaxRoute: typeof AppSettingsTaxRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppVendorsIdRoute: typeof AppVendorsIdRoute
  AppVendorsCategoriesRoute: typeof AppVendorsCategoriesRoute
  AppVendorsDocumentsRoute: typeof AppVendorsDocumentsRoute
  AppVendorsMapRoute: typeof AppVendorsMapRoute
  AppVendorsNewRoute: typeof AppVendorsNewRoute
  AppVendorsPerformanceRoute: typeof AppVendorsPerformanceRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
  AppApprovalsIndexRoute: typeof AppApprovalsIndexRoute
  AppComparisonIndexRoute: typeof AppComparisonIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppRfqsIndexRoute: typeof AppRfqsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppRiskRoute: AppRiskRoute,
  AppIndexRoute: AppIndexRoute,
  AppActivityAuditRoute: AppActivityAuditRoute,
  AppApprovalsIdRoute: AppApprovalsIdRoute,
  AppApprovalsHistoryRoute: AppApprovalsHistoryRoute,
  AppApprovalsTimelineRoute: AppApprovalsTimelineRoute,
  AppComparisonEvaluationRoute: AppComparisonEvaluationRoute,
  AppComparisonRankingRoute: AppComparisonRankingRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppNotificationsHistoryRoute: AppNotificationsHistoryRoute,
  AppPurchaseOrdersIdRoute: AppPurchaseOrdersIdRoute,
  AppPurchaseOrdersNewRoute: AppPurchaseOrdersNewRoute,
  AppQuotationsIdRoute: AppQuotationsIdRoute,
  AppQuotationsHistoryRoute: AppQuotationsHistoryRoute,
  AppQuotationsSubmitRoute: AppQuotationsSubmitRoute,
  AppReportsExportRoute: AppReportsExportRoute,
  AppReportsSpendRoute: AppReportsSpendRoute,
  AppReportsTrendsRoute: AppReportsTrendsRoute,
  AppReportsVendorsRoute: AppReportsVendorsRoute,
  AppRfqsIdRoute: AppRfqsIdRoute,
  AppRfqsNewRoute: AppRfqsNewRoute,
  AppSettingsApprovalRulesRoute: AppSettingsApprovalRulesRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsTaxRoute: AppSettingsTaxRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppVendorsIdRoute: AppVendorsIdRoute,
  AppVendorsCategoriesRoute: AppVendorsCategoriesRoute,
  AppVendorsDocumentsRoute: AppVendorsDocumentsRoute,
  AppVendorsMapRoute: AppVendorsMapRoute,
  AppVendorsNewRoute: AppVendorsNewRoute,
  AppVendorsPerformanceRoute: AppVendorsPerformanceRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
  AppApprovalsIndexRoute: AppApprovalsIndexRoute,
  AppComparisonIndexRoute: AppComparisonIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppRfqsIndexRoute: AppRfqsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
